services:
  clm-cypress-builder:
    image: clm-cypress:v.1.0.0
    container_name: clm-cypress-builder
    restart: no
    volumes:
      - ./cypress.config.ts:/app/cypress.config.ts:ro
      - ./mochawesome-report:/app/mochawesome-report